name: CI/CD Workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Smoke Test
        if: contains(github.event.pull_request.title, 'skip-build') == false
        run: |
          echo "build"
          exit 1
  build1:
    runs-on: ubuntu-latest

    steps:
      - name: test step1
        run : |
          echo "test step1"
      - name: test step1
        run : |
          echo "test step2"
  build2:
    runs-on: ubuntu-latest

    steps:
      - name: test step1
        run : |
          echo "test step1"
      - name: test step1
        run : |
          echo "test step1"
        
