name: CI/CD Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Smoke Test
        if: contains(github.event.pull_request.title, 'skip-smoke-test') == false
        run: |
          echo "smoke test"